# Generated by Django 2.1.5 on 2019-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190622_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field=1080, null=True, upload_to='uploads/%Y/%m/%d/', width_field=1920),
        ),
    ]
