# Generated by Django 2.1.3 on 2019-02-11 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20190204_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='room',
            field=models.ForeignKey(default='oldposts', on_delete=django.db.models.deletion.CASCADE, related_name='_room', to='articles.Room'),
            preserve_default=False,
        ),
    ]
