# Generated by Django 2.1.7 on 2019-02-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190210_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='room',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
